fixtures:
  repositories:
    "apache": "https://github.com/example42/puppet-apache.git"
    "stdlib": "https://github.com/puppetlabs/puppetlabs-stdlib"
    "grid_repos": "https://github.com/HEP-Puppet/grid_repos"
  symlinks:
    "nagios": "#{source_dir}"
    