language: ruby
rvm:
  - 1.8.7
script: "rake spec"
branches:
  only:
    - master
    - dev
notifications:
  email: false
gemfile: Gemfile
env:
  - PUPPET_VERSION=2.7.23 # latest 2.7; PE 2.8.0+
  - PUPPET_VERSION=3.3.2 # latest 3.3; 
